# Generated by Django 5.0.6 on 2024-05-30 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_withdraw_alter_customer_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdraw',
            old_name='receiver_email',
            new_name='email',
        ),
    ]
