# Generated by Django 5.0.6 on 2024-05-30 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0005_alter_withdraw_user'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='withdraw',
            order_with_respect_to='user',
        ),
    ]
