# Generated by Django 5.0.6 on 2024-05-30 14:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0006_alter_withdraw_order_with_respect_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='withdraw',
            unique_together={('user', 'email', 'amount', 'wallet')},
        ),
    ]
