# Generated by Django 5.0.6 on 2024-05-30 14:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0007_alter_withdraw_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='withdraw',
            unique_together={('user',)},
        ),
    ]
