# Generated by Django 5.0.6 on 2024-05-30 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0008_alter_withdraw_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='withdraw',
            unique_together=set(),
        ),
    ]
