# Generated by Django 5.0.6 on 2024-05-30 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0009_alter_withdraw_unique_together'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='withdraw',
            order_with_respect_to=None,
        ),
    ]
