# Generated by Django 5.0.6 on 2024-05-30 14:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0010_alter_withdraw_order_with_respect_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='withdraw',
            order_with_respect_to='user',
        ),
        migrations.AlterUniqueTogether(
            name='withdraw',
            unique_together={('user',)},
        ),
    ]
