# Generated by Django 5.0.6 on 2024-05-30 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0013_alter_withdraw_order_with_respect_to_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='withdraw',
            unique_together=set(),
        ),
        migrations.AlterOrderWithRespectTo(
            name='withdraw',
            order_with_respect_to=None,
        ),
    ]
