# Generated by Django 5.0.6 on 2024-05-30 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0014_alter_withdraw_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='withdraw',
            order_with_respect_to='user',
        ),
    ]
