# Generated by Django 5.0.6 on 2024-05-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0017_withdraw_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='remark',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='transaction',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='wallet',
            field=models.EmailField(choices=[('main balance', 'main balance'), ('intrest balance', 'intrest balance')], default='main balance', max_length=254),
        ),
    ]
