# Generated by Django 5.0.6 on 2024-05-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0018_withdraw_remark_withdraw_time_withdraw_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='wallet',
            field=models.CharField(choices=[('main balance', 'main balance'), ('intrest balance', 'intrest balance')], default='main balance', max_length=254),
        ),
    ]
