# Generated by Django 5.0.6 on 2024-05-31 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0019_alter_withdraw_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdraw',
            name='wallet',
        ),
    ]
