# Generated by Django 5.0.6 on 2024-05-31 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0021_withdraw_status_alter_withdraw_remark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Addfund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.CharField(blank=True, max_length=250, null=True)),
                ('gateway', models.EmailField(blank=True, max_length=254, null=True)),
                ('amount', models.CharField(blank=True, default='$10', max_length=250, null=True)),
                ('charge', models.TextField(blank=True, default='pending', max_length=250, null=True)),
                ('status', models.CharField(blank=True, max_length=250, null=True)),
                ('time', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
