# Generated by Django 5.0.6 on 2024-05-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0022_addfund'),
    ]

    operations = [
        migrations.AddField(
            model_name='addfund',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
