# Generated by Django 5.0.6 on 2024-05-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0024_remove_addfund_name_alter_addfund_gateway_payout1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout1',
            name='charge',
            field=models.CharField(blank=True, default='pending', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='payout2',
            name='charge',
            field=models.CharField(blank=True, default='pending', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='payout3',
            name='charge',
            field=models.CharField(blank=True, default='pending', max_length=250, null=True),
        ),
    ]
