# Generated by Django 5.0.6 on 2024-06-02 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0032_investment_property_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='property_name',
        ),
    ]
