# Generated by Django 5.0.6 on 2024-06-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0033_remove_investment_property_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='running_invest',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
