# Generated by Django 5.0.6 on 2024-06-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0034_investment_running_invest'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='total_invest',
            field=models.CharField(default='0', max_length=200, null=True),
        ),
    ]
