# Generated by Django 5.0.6 on 2024-06-02 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0035_deposit_total_invest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('badge1', models.CharField(choices=[('closed', 'closed'), ('open', 'open')], default='open', max_length=24)),
                ('badge2', models.CharField(choices=[('closed', 'closed'), ('open', 'open')], default='open', max_length=24)),
                ('badge3', models.CharField(choices=[('closed', 'closed'), ('open', 'open')], default='open', max_length=24)),
                ('badge4', models.CharField(choices=[('closed', 'closed'), ('open', 'open')], default='open', max_length=24)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
