# Generated by Django 5.0.6 on 2024-06-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0037_alter_badges_badge1_alter_badges_badge2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badges',
            name='bonus',
            field=models.CharField(choices=[('Level0', '0'), ('Level1', '1000'), ('Level2', '2000'), ('Level3', '5000'), ('Level4', '5000')], default='Level0', max_length=24),
        ),
    ]
