# Generated by Django 5.0.6 on 2024-06-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0038_badges_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badges',
            name='bonus',
            field=models.CharField(choices=[('0', 'Level0'), ('1000', 'Level1'), ('2000', 'Level2'), ('5000', 'Level3'), ('5000', 'Level4')], default='Level0', max_length=24),
        ),
    ]
