# Generated by Django 5.0.6 on 2024-06-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0039_alter_badges_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='badges',
            name='level',
            field=models.CharField(choices=[('X', 'X'), ('1', '1'), ('2', '2'), ('3', '4'), ('4', '4')], default='X', max_length=24),
        ),
    ]
