# Generated by Django 5.0.6 on 2024-06-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0040_badges_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
