# Generated by Django 5.0.6 on 2024-06-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0043_alter_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='avater.png', null=True, upload_to=''),
        ),
    ]
