# Generated by Django 5.0.6 on 2024-06-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0044_alter_customer_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
