# Generated by Django 5.0.6 on 2024-06-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0047_payout1_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout2',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
