# Generated by Django 5.0.6 on 2024-06-02 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0050_investment_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investment',
            options={'verbose_name': 'Investment', 'verbose_name_plural': 'Investment'},
        ),
        migrations.AlterModelOptions(
            name='payout2',
            options={'verbose_name': 'Payout2', 'verbose_name_plural': 'Payout2'},
        ),
        migrations.AlterModelOptions(
            name='payout3',
            options={'verbose_name': 'Payout3', 'verbose_name_plural': 'Payout3'},
        ),
    ]
