# Generated by Django 5.0.6 on 2024-06-02 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0051_alter_investment_options_alter_payout2_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addfund',
            options={'verbose_name': 'Addfund', 'verbose_name_plural': 'Addfund'},
        ),
        migrations.AlterModelOptions(
            name='payout1',
            options={'verbose_name': 'Payout1', 'verbose_name_plural': 'Payout1'},
        ),
        migrations.AlterModelOptions(
            name='withdraw',
            options={'verbose_name': 'Withdraw', 'verbose_name_plural': 'Withdraw'},
        ),
    ]
