# Generated by Django 5.0.6 on 2024-06-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0053_alter_addfund_options_alter_investment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='name',
            field=models.CharField(default=3, max_length=200),
            preserve_default=False,
        ),
    ]
