# Generated by Django 5.0.6 on 2024-06-03 02:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0054_alter_withdraw_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payout1',
            new_name='Banktransfer',
        ),
        migrations.RenameModel(
            old_name='Payout3',
            new_name='Bitcoin',
        ),
        migrations.RenameModel(
            old_name='Payout2',
            new_name='Wiretransfer',
        ),
        migrations.AlterModelOptions(
            name='banktransfer',
            options={'verbose_name': 'Banktransfer', 'verbose_name_plural': 'Banktransfers'},
        ),
        migrations.AlterModelOptions(
            name='bitcoin',
            options={'verbose_name': 'Bitcoin', 'verbose_name_plural': 'Bitcoins'},
        ),
        migrations.AlterModelOptions(
            name='wiretransfer',
            options={'verbose_name': 'Wiretransfer', 'verbose_name_plural': 'Wiretransfers'},
        ),
    ]
