# Generated by Django 5.0.6 on 2024-06-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0057_pin_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='status',
            field=models.CharField(choices=[('gif/successfull-payment.gif', 'gif/successfull-payment.gif'), ('pending.png', 'pending.png')], default='/pending.png', max_length=240),
        ),
    ]
