from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    path ('', views.index, name = "index"),
    path ('about/', views.about, name = "about"),
    path ('add_fund/', views.add_fund, name = "add_fund"),
    path ('add_fund_confirm/', views.add_fund_confirm, name = "add_fund_confirm"),
    path ('badges/', views.badges, name = "badges"),
    path ('contact/', views.contact, name = "contact"),
    path ('create/', views.create, name = "create"),
    path ('dashboard/', views.dashboard, name = "dashboard"),
    path ('faqs/', views.faqs, name = "faqs"),
    path ('fund_history/', views.fund_history, name = "fund_history"),
    path ('get_started/', views.get_started, name = "get_started"),
    path ('invest_history/', views.invest_history, name = "invest_history"),
    path ('investment_properties/', views.investment_properties, name = "investment_properties"),
    path ('investprime_support_ticket/', views.investprime_support_ticket, name = "investprime_support_ticket"),
    path ('money_transfer/', views.money_transfer, name = "money_transfer"),
    path ('my_investment_properties/', views.my_investment_properties, name = "my_investment_properties"),
    path ('my_offered_properties/', views.my_offered_properties, name = "my_offered_properties"),
    path ('my_shared_properties/', views.my_shared_properties, name = "my_shared_properties"),
    path ('payout_history/', views.payout_history, name = "payout_history"),
    path ('payout/', views.payout, name = "payout"),
    path ('payout1/', views.payout1, name = "payout1"),
    path ('payout2/', views.payout2, name = "payout2"),
    path ('payout3/', views.payout3, name = "payout3"),
    path ('pricing/', views.pricing, name = "pricing"),
    path ('profile/', views.profile, name = "profile"),
    path ('property_share_market/', views.property_share_market, name = "property_share_market"),
    path ('receive_offered_properties/', views.receive_offered_properties, name = "receive_offered_properties"),
    path ('referral_bonus/', views.referral_bonus, name = "referral_bonus"),
    path ('referral/', views.referral, name = "referral"),
    path ('register/', views.register, name = "register"),
    path ('login/', views.custom_login, name = "login"),
    path ('logout/', views.custom_logout, name = "logout"),
    path("password_reset", views.password_reset, name="password_reset"),
    path ('service/', views.service, name = "service"),
    path ('add_fund_confirm1/', views.add_fund_confirm1, name = "add_fund_confirm1"),
    path ('transaction/', views.transaction, name = "transaction"),
    path ('learn_more/', views.learn_more, name = "learn_more"),
    path ('crypto_fx/', views.crypto_fx, name = "crypto_fx"),
    path ('wish_list_property/', views.wish_list_property, name = "wish_list_property"),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('template_activate_account', views.template_activate_account, name='template_activate_account'),
    path("change_password", views.change_password, name="change_password"),
    path('reset/<uidb64>/<token>', views.passwordResetConfirm, name='password_reset_confirm'),
    path('photo/<str:pk>/', views.viewPhoto, name='photo'),
    path ('make_investement/', views.make_investement, name = "make_investement"),
    path ('pin/', views.pin, name = "pin"),
    path ('pay-successfully/', views.pay_successfully, name = "pay-successfully"),
    path ('Identity_verification/', views.Identity_verification, name = "Identity_verification"),
    
]